# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser_score', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('trueskill_date_time', models.DateTimeField()),
                ('trueskill_sigma', models.FloatField()),
                ('trueskill_gamma', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='gameresult',
            name='loser_back',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_back_game_results', to='skills.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='loser_front',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_front_game_results', to='skills.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='winner_back',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_back_game_results', to='skills.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='winner_front',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_front_game_results', to='skills.Player'),
        ),
    ]
