# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 22:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20170529_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='trueskill_date_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trueskill_mu',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trueskill_sigma',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='loser_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
